import { MercadoPagoAdditionalInfo } from "./AdditionalInfo";
import { MercadoPagoCardInfo } from "./CardInfo";
import { MercadoPagoChargeDetail } from "./ChargeDetail";
import { ChargesExecutionInfo } from "./ChargesExecutionInfo";
import { MercadoPagoFeeDetail } from "./FeeDetail";
import { MercadoPagoOrder } from "./Order";
import { MercadoPagoPaymentMethod } from "./PaymentMethod";
import { MercadoPagoPointOfInteraction } from "./PointOfInteraction";
import { MercadoPagoPaymentPayer, MercadoPagoTransactionDetails } from "./TransactionDetails";


export type MercadoPagoPaymentShape = {
  _last: {
    charges_execution_info: ChargesExecutionInfo;
  };
  charges_execution_info: ChargesExecutionInfo;
  error: null;
  _pagination_params: null;
  _empty: boolean;
  id: number;
  acquirer: null;
  acquirer_reconciliation: [];
  site_id: string | null;
  sponsor_id: number | null;
  operation_type: string;
  order_id: string | null;
  order: MercadoPagoOrder;
  binary_mode: boolean;
  external_reference: string | null;
  status: string;
  status_detail: string;
  store_id: string | null;
  taxes_amount: number;
  payment_type: string | null;
  date_created: string;
  last_modified: string | null;
  live_mode: boolean;
  date_last_updated: string;
  date_of_expiration: string | null;
  deduction_schema: null;
  date_approved: string;
  money_release_date: string;
  money_release_days: number | null;
  money_release_schema: null;
  money_release_status: string;
  currency_id: string;
  transaction_amount: number;
  transaction_amount_refunded: number;
  shipping_cost: number | null;
  total_paid_amount: number | null;
  finance_charge: number | null;
  net_received_amount: number | null;
  marketplace: string | null;
  marketplace_fee: number | null;
  reason: string | null;
  payer: MercadoPagoPaymentPayer;
  collector: null;
  collector_id: number;
  counter_currency: string | null;
  payment_method_id: string;
  payment_type_id: string;
  pos_id: number | null;
  transaction_details: MercadoPagoTransactionDetails;
  fee_details: MercadoPagoFeeDetail[];
  differential_pricing_id: number | null;
  application_fee: number | null;
  authorization_code: string;
  capture: boolean | null;
  captured: boolean;
  card: MercadoPagoCardInfo;
  call_for_authorize_id: string | null;
  statement_descriptor: string;
  refunds: [];
  shipping_amount: number;
  additional_info: MercadoPagoAdditionalInfo;
  campaign_id: number | null;
  coupon_amount: number;
  installments: number;
  token: string | null;
  description: string;
  notification_url: string | null;
  issuer_id: string;
  processing_mode: string;
  merchant_account_id: string | null;
  merchant_number: string | null;
  metadata: {
    reference: string;
    client_id: number;
  };
  callback_url: string | null;
  amount_refunded: number | null;
  coupon_code: string | null;
  barcode: null;
  marketplace_owner: string | null;
  integrator_id: string | null;
  corporation_id: string | null;
  platform_id: string | null;
  charges_details: MercadoPagoChargeDetail[];
  taxes: number | null;
  net_amount: number | null;
  point_of_interaction: MercadoPagoPointOfInteraction;
  payment_method_option_id: string | null;
  merchant_services: null;
  build_version: string;
  payment_method: MercadoPagoPaymentMethod;
};
