export const dashboardFormsTranslations = {
  text_name_description:
    "Search using a partial value of the name or description",
  text_started_at_description:
    "Search by the month when the registration period started",
  text_expired_at_description:
    "Search by the month when the registration period ended",
  text_filters:
    "Use the filters below to refine the form search",
  about_thanks_message:
    "Write instructions or information to be displayed after the form is submitted",
  text_already_exclude:
    "By continuing, the data linked to this record will be deleted from the system.",
  title_already_exclude: "Do you want to delete this record?",
  fills: {
    text_already_exclude:
      "By continuing, the data linked to this record will be deleted from the system.",
    title_already_exclude: "Do you want to delete this record?",
  },
  about_relation_category:
    "The category selected above will be linked to the clients generated by this form.",
};
