export const publicRoutes = {
  access: "/access",
  login: "/login",
  forgotPassword: "/forgot-password",
  successful: "/successful",
  forms: "/forms",
  agencies: "/agencies",
  checkout: "/checkout",
  tours: "/tours",
  galleries: "/galleries",
};
export const privateAgencyRoutes = {
  overview: "/panel/overview",
  charges: "/panel/charges",
  sales: "/panel/sales",
  statics: "/panel/statics",
  tours: "/panel/tours",
  logout: "/panel/logout",
  settings: "/panel/settings",
};

export const privateRoutes = {
  panel: privateAgencyRoutes,
  dashboard: "/dashboard/overview",
  clients: "/dashboard/clients",
  agencies: "/dashboard/agencies",
  sales: "/dashboard/sales",
  operations: "/dashboard/operations",
  statics: "/dashboard/statics",
  tours: "/dashboard/tours",
  dispatcher: "/dashboard/dispatcher",
  subscribers: "/dashboard/subscribers",
  forms: "/dashboard/forms",
  schedule: "/dashboard/schedule",
  galleries: "/dashboard/galleries",
  finance: "/dashboard/charges",
  charges: "/dashboard/charges",
  financesCreate: "/dashboard/charges/create",
  financePayments: "/dashboard/charges/{id}/payment/{payment_id}",
  usersManager: "/dashboard/users",
  userGroups: "/dashboard/groups",
  apisManager: "/dashboard/apis",
  settings: "/dashboard/settings",
  logout: "/dashboard/logout",
};
